name: validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML
        run: |
          pip install yamllint
          yamllint -d "{extends: relaxed, rules: {line-length: disable}}" detections policies
